### PR TITLE
Updated for Fujitsu 4mb Fram/commented out serial.prints/Added fix for QPINAND

### PR DESCRIPTION
**Pull request by mjs513**
@PaulStoffregen 
Updated for new Fram chip + commented out extra serial.print's for debugging in Fram Begin.

### CODE REVIEW

**Comment by mjs513** [comment]
@PaulStoffregen 

This is a fix for QPINAND getMediaName issue as identified here: https://forum.pjrc.com/index.php?threads/littlefs_qpinand-getmedianame-broken.74854/

not sure how to answer jmarsh.

**Comment by PaulStoffregen** [comment]
I'm going to merge this now for the fixes, but LittleFS_NAND.cpp needs work.  The FlexSPI2 LUTs should be fully initialized by the begin() function.  Before writing, the unlock registers need to be written.  The LUTs really should not be written by other places.

**Comment by PaulStoffregen** [comment]
Also a separate issue, looks like most of the getMediaName() functions aren't properly checking whether chip_lookup() returns nullptr.

**Comment by mjs513** [comment]
@PaulStoffregen  - @KurtE

>Also a separate issue, looks like most of the getMediaName() functions aren't properly checking whether chip_lookup() returns nullptr.

Saw that in the original post as well.  However, didn't worry about it since before you even get to media name you have 
`if (!info) return false;`
in all the begins.  So if the chip isn't there its going to return false.  So there shouldn't be an nullptr media names.

>LittleFS_NAND.cpp needs work. The FlexSPI2 LUTs should be fully initialized by the begin() function. Before writing, the unlock registers need to be written. The LUTs really should not be written by other places.

thats going to require some work.  Probably have to restructure the NAND stuff.  If I remember right had to redefine some along the way other wise I ran out available LUTs.

But will start looking at fixing it in the morning, day is pretty much over for me now :)  Getting ready for dinner.

**Comment by PaulStoffregen** [comment]
No worries on timeframe for NAND.

**Comment by mjs513** [comment]
Hi Paul
Decided to try and fix the nand.  Here is the issue, if I put in additional luts over CMD 15( lut 15):
```
  // cmd index 16 = read Status register #1 SPI, 0x05
  FLEXSPI2_LUT64 = LUT0(CMD_SDR, PINS1, 0x05) | LUT1(CMD_SDR, PINS1, reg);  
  FLEXSPI2_LUT65 = LUT0(READ_SDR, PINS1, 1);
  
  // cmd index 17 = read Status register #1 SPI
  FLEXSPI2_LUT68 = LUT0(CMD_SDR, PINS1, 0x01) | LUT1(CMD_SDR, PINS1, reg);
  FLEXSPI2_LUT69 = LUT0(WRITE_SDR, PINS1, 1);
  
  //CMD Index 18 , Write enable 0x06 
  FLEXSPI2_LUT72 = LUT0(CMD_SDR, PINS1, 0x06);
  
	// cmd index 19, Block Erase 0xD8
	FLEXSPI2_LUT76 = LUT0(CMD_SDR, PINS1, 0xD8) | LUT1(ADDR_SDR, PINS1, 0x18);
```
    I will get compile errors (probably because lut table entries exceeded).  Thats pretty much why I reused cmds.  Note: CMD 0-6 are used in startup.c.
    
```
C:\Users\Merli\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.59.0\libraries\LittleFS\src\LittleFS_NAND.cpp:1025:3: error: 'FLEXSPI2_LUT64' was not declared in this scope; did you mean 'FLEXSPI2_LUT4'?
 1025 |   FLEXSPI2_LUT64 = LUT0(CMD_SDR, PINS1, 0x05) | LUT1(CMD_SDR, PINS1, reg);
      |   ^~~~~~~~~~~~~~
      |   FLEXSPI2_LUT4
In file included from C:\Users\Merli\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/core_pins.h:32,
                 from C:\Users\Merli\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/wiring.h:39,
                 from C:\Users\Merli\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/WProgram.h:46,
                 from C:\Users\Merli\AppData\Local\Temp\arduino\sketches\15885B65D7823EB60DCD2189C3355E6F\pch\Arduino.h:6:
C:\Users\Merli\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.59.0\libraries\LittleFS\src\LittleFS_NAND.cpp:1025:70: error: 'reg' was not declared in this scope
 1025 |   FLEXSPI2_LUT64 = LUT0(CMD_SDR, PINS1, 0x05) | LUT1(CMD_SDR, PINS1, reg);
      |                                                                      ^~~
C:\Users\Merli\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.59.0\cores\teensy4/imxrt.h:5454:64: note: in definition of macro 'FLEXSPI_LUT_INSTRUCTION'
 5454 |         (((opcode) & 0x3F) << 10) | (((pads) & 0x03) << 8) | ((operand) & 0xFF)))
      |                                                                ^~~~~~~
C:\Users\Merli\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.59.0\libraries\LittleFS\src\LittleFS_NAND.cpp:1025:49: note: in expansion of macro 'LUT1'
 1025 |   FLEXSPI2_LUT64 = LUT0(CMD_SDR, PINS1, 0x05) | LUT1(CMD_SDR, PINS1, reg);
      |                                                 ^~~~
C:\Users\Merli\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.59.0\libraries\LittleFS\src\LittleFS_NAND.cpp:1026:3: error: 'FLEXSPI2_LUT65' was not declared in this scope; did you mean 'FLEXSPI2_LUT25'?
 1026 |   FLEXSPI2_LUT65 = LUT0(READ_SDR, PINS1, 1);
      |   ^~~~~~~~~~~~~~
      |   FLEXSPI2_LUT25
C:\Users\Merli\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.59.0\libraries\LittleFS\src\LittleFS_NAND.cpp:1029:3: error: 'FLEXSPI2_LUT68' was not declared in this scope; did you mean 'FLEXSPI2_LUT6'?
 1029 |   FLEXSPI2_LUT68 = LUT0(CMD_SDR, PINS1, 0x01) | LUT1(CMD_SDR, PINS1, reg);
      |   ^~~~~~~~~~~~~~
      |   FLEXSPI2_LUT6
C:\Users\Merli\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.59.0\libraries\LittleFS\src\LittleFS_NAND.cpp:1030:3: error: 'FLEXSPI2_LUT69' was not declared in this scope; did you mean 'FLEXSPI2_LUT19'?
 1030 |   FLEXSPI2_LUT69 = LUT0(WRITE_SDR, PINS1, 1);
      |   ^~~~~~~~~~~~~~
      |   FLEXSPI2_LUT19
C:\Users\Merli\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.59.0\libraries\LittleFS\src\LittleFS_NAND.cpp:1033:3: error: 'FLEXSPI2_LUT72' was not declared in this scope; did you mean 'FLEXSPI2_LUT27'?
 1033 |   FLEXSPI2_LUT72 = LUT0(CMD_SDR, PINS1, 0x06);
      |   ^~~~~~~~~~~~~~
      |   FLEXSPI2_LUT27
C:\Users\Merli\AppData\Local\Arduino15\packages\teensy\hardware\avr\1.59.0\libraries\LittleFS\src\LittleFS_NAND.cpp:1036:9: error: 'FLEXSPI2_LUT76' was not declared in this scope; did you mean 'FLEXSPI2_LUT6'?
 1036 |         FLEXSPI2_LUT76 = LUT0(CMD_SDR, PINS1, 0xD8) | LUT1(ADDR_SDR, PINS1, 0x18);
      |         ^~~~~~~~~~~~~~
      |         FLEXSPI2_LUT6

exit status 1

Compilation error: exit status 1
```

or am I missing something in setup

**Comment by KurtE** [comment]
@mjs513 @PaulStoffregen - Sorry the FlexSPI2 stuff is beyond my pay grade. :wink: and knowledge.

But I believe there are only 64 (0-63) LUT's per FlexSPIx object?  

No idea on how to fix?  Can the LUTs be reused?  Can they be dynamically allocated?  That is if we are trying to support 10 different devices, each needing several slots, Is there a way to allocate them, such that maybe only those one(s) that are used on the actual board are allocated?  Or is that somewhat already assumed?  That is there are only a few valid setups:  with 0, 1, or two PSRAM and 0 or 1 flash chips?

**Comment by mjs513** [comment]
@KurtE - @PaulStoffregen 

>But I believe there are only 64 (0-63) LUT's per FlexSPIx object?
was just looking at it again and seems its a hard limit as you indicated.

As to the question about luts being able to be reused.  Thats kind of what I am doing now with the NAND api.  It redefines LUTs as its being called.

Did see something where uTasker is using different lut tables - but not sure if its worth the effort: https://community.nxp.com/t5/i-MX-RT-Crossover-MCUs/Usage-of-FlexSPI-LUT-in-i-MXRT/m-p/860245

**Pull request merged**
