### PR TITLE
added rename/format(spi,qspi) to littlefs

### PR DESCRIPTION
**Pull request by mjs513**
Paul
Know you are busy as heck so I went ahead and tried adding in format(spi and qspi) and rename commands for LittleFs.  Looks like they are working from my limited testing so far.  Seems to be working with MTP for LittleFS as well.

Mike

### CODE REVIEW

**Comment by PaulStoffregen** [comment]
The format function should probably first check the configured boolean.  If we already have a filesystem mounted, should probably unmount and give lfs an opportunity to do whatever de-allocation it does.

**Comment by mjs513** [comment]
I will play around with that next - put on my todo list which is nothing like yours :)

**Comment by Defragster** [comment]
Format worked here to clear QSPI ghost directories that otherwise recur.

**As long as** the Teensy doesn't repower or 'SCB_AIRCR = 0x05FA0004' before use - otherwise the ghosts persist. Is there some flush needed to commit something?

**Comment by Defragster** [comment]
Also perhaps correct spelling of : attemping   as in attempting

**Pull request merged**
