### PR TITLE
Add simple wrapper classes for SPI and QSPI

### PR DESCRIPTION
**Pull request by KurtE**
@PaulStoffregen  @mjs513  @Defragster 

As mentioned earlier on forum thread, here is the simple wrappers I have been using.   

Note: I had/have to modify the few sketches that have their own copies of these...

So if you are not sure which type of storage you might have on your different boards, you can use the combine class which includes a member of the different known littlefs clases for SPI or QSPI and the begin method  will check one after another until their begin method succeeds

### CODE REVIEW

**Comment by KurtE** [comment]
@PaulStoffregen  (and all)
I was debating with myself on class names... 
Currently I have: lfs_qspi and lfs_spi

Alternative  are names like LittleFS_SPI  which may make more sense, other than they don't themselves derive from LittleFs class

**Comment by PaulStoffregen** [comment]
Please use LittleFS_SPI and LittleFS_QSPI.

As a bare minimum, these need to inherit FS.  Did something turn out to be impractical about inheriting from LittleFS class?

**Comment by KurtE** [comment]
I had an earlier version like this that I will reproduce.
Feel safer deriving from FS, but will still leave a call to get the LittleFS...

**Comment by PaulStoffregen** [comment]
FS should be fine, just so we can pass instances of these wrapper classes to MTP (and other stuff which will access filesystems).

I need to work on an urgent test fixture issue right now (the joys of manufacturing) but should be able to work on this later today.

**Comment by KurtE** [comment]
I just pushed up new version that is based off of FS class, I then do overrides of all of the FS methods.

Not sure what you will think of the way to bypass having to check for NULL in these methods....

**Comment by PaulStoffregen** [comment]
Merging this now.  But looks like usedSize() and totalSize() might need a little more work?

**Comment by KurtE** [comment]
Yep missed those simply pfs->calls will do in morning

**Comment by PaulStoffregen** [comment]
Pretty soon I need to package up a stable 1.56 release.  Definitely want to get this in.  The USB host MSC stuff probably also makes sense for 1.56, but I want to review the public API before merging.  Will do that today or this weekend.

**Comment by KurtE** [comment]
Pushed up fix #40 to the used/total sizes also ran it through using MTP test sketch

**Pull request merged**
